services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/bobber
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/bobber

  mysql:
    image: mysql:9.4
    container_name: bobber-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bobber
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
